-- CREATE TABLE todos (
--    id BIGINT NOT NULL AUTO_INCREMENT,
--    title VARCHAR(255) NOT NULL,
    -- category VARCHAR(255) NOT NULL,
    -- description TEXT,
    -- completed BOOLEAN DEFAULT FALSE,
    -- created_at TIMESTAMP,
    -- updated_at TIMESTAMP,
    -- PRIMARY KEY (id)
-- );